# Generated by Django 4.2.9 on 2026-05-06

from django.db import migrations
import cloudinary.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rentalrequest_driver_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
